const assets=window.ASSET_CATALOG.assets;
const names={'pose':'Character poses','character-art':'Character art','model':'3D models','model-preview':'Model previews','texture':'Textures','coloring':'Coloring sheets','gameplay-reference':'Gameplay references','merchandise-reference':'Merchandise references','illustration-reference':'Illustration references'};
let character='all';const $=s=>document.querySelector(s);
$('#total').textContent=assets.length;
for(const cat of [...new Set(assets.map(a=>a.category))].sort()){const o=document.createElement('option');o.value=cat;o.textContent=names[cat]||cat;$('#category').append(o);}
const format=a=>a.path.split('.').pop().toUpperCase();
const size=a=>a.bytes>1048576?(a.bytes/1048576).toFixed(1)+' MB':Math.round(a.bytes/1024)+' KB';
function preview(a){$('#largeImage').src=a.preview||a.path;$('#largeImage').alt=a.title;$('#previewType').textContent=names[a.category]||a.category;$('#previewTitle').textContent=a.title;$('#previewMeta').textContent=[format(a),a.width?`${a.width} × ${a.height}`:'OBJ mesh',size(a),a.source_type==='official'?'Official website':'Community wiki'].join(' · ');$('#previewRights').textContent=a.rights;$('#download').href=a.path;$('#download').download=a.path.split('/').pop();$('#sourceLink').href=a.source_page;$('#preview').showModal();}
function link(text,href,download=false){const a=document.createElement('a');a.textContent=text;a.href=href;if(download)a.download=href.split('/').pop();else{a.target='_blank';a.rel='noopener';}return a;}
function render(){const q=$('#search').value.toLowerCase().trim(),cat=$('#category').value,source=$('#source').value;const list=assets.filter(a=>(character==='all'||a.characters.includes(character))&&(cat==='all'||a.category===cat)&&(source==='all'||a.source_type===source)&&[a.title,a.id,a.category,...a.characters,format(a)].join(' ').toLowerCase().includes(q));$('#resultCount').textContent=list.length;$('#empty').hidden=!!list.length;const frag=document.createDocumentFragment();for(const a of list){const card=document.createElement('article');card.className='card';const b=document.createElement('button');b.className='image-button';b.ariaLabel='Preview '+a.title;b.onclick=()=>preview(a);const img=document.createElement('img');img.src=a.thumbnail||a.preview||a.path;img.alt=a.title;img.loading='lazy';img.decoding='async';const badge=document.createElement('span');badge.className='badge';badge.textContent=format(a);b.append(img,badge);const body=document.createElement('div');body.className='card-text';const title=document.createElement('h3');title.textContent=a.title;const meta=document.createElement('div');meta.className='card-meta';const label=document.createElement('span');label.textContent=names[a.category]||a.category;const res=document.createElement('span');res.textContent=a.width?`${a.width}×${a.height}`:'3D';meta.append(label,res);const links=document.createElement('div');links.className='card-links';links.append(link('Download ↓',a.path,true),link('Source ↗',a.source_page));body.append(title,meta,links);card.append(b,body);frag.append(card);}$('#grid').replaceChildren(frag);}
document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{character=b.dataset.character;document.querySelectorAll('[data-character]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});render();});$('#search').oninput=render;$('#category').onchange=render;$('#source').onchange=render;$('#close').onclick=()=>$('#preview').close();$('#preview').onclick=e=>{if(e.target===$('#preview'))$('#preview').close();};render();
